### ISSUE TITLE
Задачи проектировщика

### ISSUE THREAD

**Issue by DaryaSharovaRI311050** [DaryaSharovaRI311050/Baies#4]
1. Придумать и обосновать архитектуру продукта
2. Написать требования к системному ПО (ОС, СУБД)
3. Разработать и оформить архитектурные диаграммы из issue https://github.com/DaryaSharovaRI311050/Baies/issues/3
4. Подготовить часть пояснительной записки и отчитаться в issue https://github.com/DaryaSharovaRI311050/Baies/issues/1
5. Добавить файлы в репозиторий
6. Выдать руководителю отчет о выполнении

**Comment by Llarioh** [comment]
Архитектура придумана и обоснована

**Comment by Llarioh** [comment]
Составлены системные требования

**Comment by Llarioh** [comment]
Разработана и оформленна архитектурная диаграмма

**Comment by Llarioh** [comment]
Разработана и оформлена функциональная диаграмма

**Comment by Llarioh** [comment]
Разработана и оформлена диаграмма последовательности работы программы

**Comment by Llarioh** [comment]
Файлы добавлены в репозиторий
