### ISSUE TITLE
Задачи разработчика

### ISSUE THREAD

**Issue by DaryaSharovaRI311050** [DaryaSharovaRI311050/Baies#5]
1. Выбрать язык программирования и обосновать выбор
2. Реализовать проект
3. Протестировать продукт
4. Разработать и оформить архитектурные диаграммы из issue https://github.com/DaryaSharovaRI311050/Baies/issues/3
5. Подготовить часть пояснительной записки и отчитаться в issue https://github.com/DaryaSharovaRI311050/Baies/issues/1
6. Добавить файлы в репозиторий
7. Выдать руководителю отчет о выполнении

**Comment by RileySamos** [comment]
Листинг кода:
[Листинг кодов.docx](https://github.com/DaryaSharovaRI311050/Baies/files/13874145/default.docx)

**Comment by DaryaSharovaRI311050** [comment]
Пояснение: разработчик отчитывался обо всех моментах работы в личных сообщениях, а также залил необходимые файлы на гит
